# Generated by Django 5.2.7 on 2025-10-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_at',
        ),
        migrations.AddField(
            model_name='trip',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
