# Generated by Django 5.2.7 on 2025-10-14 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='planner.trip'),
            preserve_default=False,
        ),
    ]
